version: "3"
services:
  # Alacrity services
  alacrity_geth: # Ethereum test network
    build:
      context: ..
      dockerfile: docker/containers/alacrity_geth/Dockerfile
    image: gcr.io/legicash-demo-1950/legicash-demo/alacrity_geth:v1.8.21
    hostname: "alacrity-geth"
    container_name: "alacrity-geth"
    volumes:
      - /tmp/:/var/www/app/alacrity-geth/_ethereum
      - /tmp/:/var/www/app/alacrity-geth/_run/logs
    networks:
      legicash-demo:
        ipv4_address: 10.5.0.9
    ports:
      - "8545:8545"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8545"]
        interval: 30s
        timeout: 10s
        retries: 5

  alacrity_prereq: 
    build:
      context: ..
      dockerfile: docker/containers/build_prerequisites/Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: gcr.io/legicash-demo-1950/legicash-demo/alacrity_build_prerequisites:${TAG:-latest}
    hostname: "alacrity-prereq"
    container_name: "alacrity-prereq"
    environment:
      - STACK_YAML=../../hs/alacrity/stack.yaml
    command: /bin/true
    networks:
      legicash-demo:
        ipv4_address: 10.5.0.10

  alacrity_dev: 
    build:
      context: ..
      dockerfile: docker/containers/alacrity_dev/Dockerfile
    image: gcr.io/legicash-demo-1950/legicash-demo/alacrity_dev:${TAG:-latest}
    hostname: "alacrity-dev"
    container_name: "alacrity-dev"
    environment:
      - STACK_YAML=../../hs/alacrity/stack.yaml
      - ETH_NODE_URI=http://alacrity-geth:8545
    command: ghcid
    volumes:
      - ../:/opt/alacrity/project
    networks:
      legicash-demo:
        ipv4_address: 10.5.0.11

  alacrity_demo: 
    build:
      context: ..
      dockerfile: docker/containers/alacrity_demo/Dockerfile
      args:
        UID: 1000
        GID: 1000
    image: gcr.io/legicash-demo-1950/legicash-demo/alacrity_demo:${TAG:-latest}
    hostname: "alacrity-demo"
    container_name: "alacrity-demo"
    volumes:
      - ../examples/rps-auto:/opt/alacrity/project/examples/rps-auto
    environment:
      - STACK_YAML=../../hs/alacrity/stack.yaml
      - ETH_NODE_URI=http://alacrity-geth:8545
    command: >
      /bin/bash -c "
        sleep 8;
        npm clean-install;
        make lint test demo
      "
    networks:
      legicash-demo:
        ipv4_address: 10.5.0.12
    depends_on:
    - "alacrity_geth"

networks:
  legicash-demo:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24
