name:                alacrity
version:             0.1.0.0
github:              "AlacrisIO/alacrity"
license:             BSD3
author:              "Alacris"
maintainer:          "jay@alacris.io"
copyright:           "2019 Alacris"

extra-source-files:
- README.md
- ChangeLog.md
- ala/*.ala

description:         Please see the README on GitHub at <https://github.com/AlacrisIO/alacrity#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- prettyprinter
- megaparsec
- parser-combinators
- bytestring
- mtl
- filepath
- directory
- file-embed >= 0.0.9
- process
- pretty-simple
- text
- debug
- extra
- simple-smt
- aeson
- unordered-containers

ghc-options:
- -Wall
- -Werror
- -O2

library:
  source-dirs: src

executables:
  alacrityc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alacrity

tests:
  alacrity-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alacrity
