FROM debian:oldstable

LABEL maintainer="vedr@nlebo.com"

# Install dependencies.
RUN apt-get update && \
  apt-get install -y  \
  curl gcc libgmp-dev libpq-dev make cmake xz-utils \
  zlib1g-dev wget unzip software-properties-common gnupg git sudo \
  libboost-all-dev libleveldb-dev libcurl4-openssl-dev \
  libmicrohttpd-dev libminiupnpc-dev libgmp-dev

RUN mkdir -p /opt/alacrity/project

# Add and use non-root user
RUN groupadd -g 1100 appuser && \
    useradd  -m -r -u 1100 -g appuser appuser
#USER appuser
WORKDIR /opt/alacrity

# Install Stack.
RUN curl --location https://www.stackage.org/stack/linux-x86_64-static > stack.tar.gz && \
  tar xf stack.tar.gz && \
  cp stack-*-linux-x86_64-static/stack /usr/local/bin/stack && \
  rm -f -r stack.tar.gz stack-*-linux-x86_64-static/stack && \
  stack --version

# Install z3
RUN wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-debian-8.11.zip
RUN unzip z3-4.8.4.d6df51951f4c-x64-debian-8.11.zip
ENV PATH /home/appuser/z3-4.8.4.d6df51951f4c-x64-debian-8.11/bin:${PATH}

# boost
RUN wget http://sourceforge.net/projects/boost/files/boost/1.65.0/boost_1_65_0.tar.gz
RUN tar -xf boost_1_65_0.tar.gz
RUN cd boost_1_65_0 && ./bootstrap.sh && ./b2 && ./bjam install

# Install solc
USER root
RUN git clone --recursive https://github.com/ethereum/solidity.git
RUN cd solidity && git submodule update --init --recursive
RUN cd solidity && ./scripts/install_deps.sh
RUN cd solidity && ./scripts/build.sh

COPY . /opt/alacrity/project
#RUN cd examples/rps-auto && make

# ENV BOOST_ROOT /usr/local/include/boost/

